# This file exists solely to coordinate the build of Grapl service
# containers.
#
# At the moment, these are "local" Grapl containers, and not
# necessarily identical to the artifacts we would use in real
# deployments.
version: "3.8"

services:
  ########################################################################
  # Rust Services
  ########################################################################

  sysmon-subgraph-generator:
    image: ${REGISTRY:-grapl}/sysmon-subgraph-generator:${TAG:-latest}
    build:
      context: src
      dockerfile: rust/Dockerfile
      target: sysmon-subgraph-generator-deploy
      args:
        - RUST_BUILD=${RUST_BUILD:-debug}

  osquery-subgraph-generator:
    image: ${REGISTRY:-grapl}/osquery-subgraph-generator:${TAG:-latest}
    build:
      context: src
      dockerfile: rust/Dockerfile
      target: osquery-subgraph-generator-deploy
      args:
        - RUST_BUILD=${RUST_BUILD:-debug}

  node-identifier:
    image: ${REGISTRY:-grapl}/node-identifier:${TAG:-latest}
    build:
      context: src
      dockerfile: rust/Dockerfile
      target: node-identifier-deploy
      args:
        - RUST_BUILD=${RUST_BUILD:-debug}

  node-identifier-retry:
    image: ${REGISTRY:-grapl}/node-identifier-retry:${TAG:-latest}
    build:
      context: src
      dockerfile: rust/Dockerfile
      target: node-identifier-retry-deploy
      args:
        - RUST_BUILD=${RUST_BUILD:-debug}

  graph-merger:
    image: ${REGISTRY:-grapl}/graph-merger:${TAG:-latest}
    build:
      context: src
      dockerfile: rust/Dockerfile
      target: graph-merger-deploy
      args:
        - RUST_BUILD=${RUST_BUILD:-debug}

  analyzer-dispatcher:
    image: ${REGISTRY:-grapl}/analyzer-dispatcher:${TAG:-latest}
    build:
      context: src
      dockerfile: rust/Dockerfile
      target: analyzer-dispatcher-deploy
      args:
        - RUST_BUILD=${RUST_BUILD:-debug}

  ########################################################################
  # Python Services
  ########################################################################

  analyzer-executor:
    image: ${REGISTRY:-grapl}/analyzer-executor:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: analyzer-executor-deploy

  model-plugin-deployer:
    image: ${REGISTRY:-grapl}/model-plugin-deployer:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: model-plugin-deployer-deploy

  ########################################################################
  # Web Services
  ########################################################################

  engagement-view-uploader:
    image: ${REGISTRY:-grapl}/engagement-view:${TAG:-latest}
    build:
      context: src
      dockerfile: js/engagement_view/Dockerfile
      target: engagement-view-local-deploy

  graphql-endpoint:
    image: ${REGISTRY:-grapl}/graphql-endpoint:${TAG:-latest}
    build:
      context: src
      dockerfile: js/graphql_endpoint/Dockerfile
      target: graphql-endpoint-deploy

  notebook:
    image: ${REGISTRY:-grapl}/notebook:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: grapl-notebook

  ########################################################################
  # Utility Services
  ########################################################################

  pulumi:
    image: ${REGISTRY:-grapl}/local-pulumi:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.pulumi

  provisioner:
    image: ${REGISTRY:-grapl}/provisioner:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/provisioner/provisioner.Dockerfile
      args:
        - TAG=${TAG:-latest}
