[package]
name = "grapl-router-api"
version = "0.1.0"
authors = ["grapl <andrea@graplsecurity.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
env_logger = "0.6"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
http = "0.1.19"
