[package]
name = "grapl-api-service"
version = "0.1.0"
authors = ["grapl <andrea@graplsecurity.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
