---
steps:

  # Tries to go to private s3 bucket, fails, as expected
  - label: "Internal upload, keep assumed role"
    command: artifact_test.sh
    env:
      DROP_ASSUMED_ROLE: false
      UPLOAD_FILE_IN_COMMAND: true
    agents:
      queue: "packer-staging"

  # Tries to go to private s3 bucket, succeeds, as expected
  - label: "Internal upload, drop assumed role"
    command: artifact_test.sh
    env:
      DROP_ASSUMED_ROLE: true
      UPLOAD_FILE_IN_COMMAND: true
    agents:
      queue: "packer-staging"

  # Tries to go to private S3 bucket, fails
  - label: "External upload, keep assumed role"
    command: artifact_test.sh
    env:
      DROP_ASSUMED_ROLE: false
      UPLOAD_FILE_IN_COMMAND: false
    agents:
      queue: "packer-staging"
    artifact_paths:
      - "test.txt"

  # Tries to go to private S3 bucket, fails unexpectedly
  - label: "External upload, drop assumed role"
    command: artifact_test.sh
    env:
      DROP_ASSUMED_ROLE: true
      UPLOAD_FILE_IN_COMMAND: false
    agents:
      queue: "packer-staging"
    artifact_paths:
      - "test.txt"
