[package]
name = "grapl-graph-descriptions"
version = "0.2.10"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"
description = "A library for interacting with Grapl graphs"
license = "MIT"

[dependencies]
thiserror = "1"

prost = "0.7"
prost-derive = "0.7"
prost-types = "0.7"

serde = "1"
serde_json = "1"
serde_derive = "1"

derive_builder = "0.9"
dgraph-tonic = "0.8"

log = "0.4"
dgraph_query_lib = "0.1"
futures-retry = "0.5"
anyhow = "*"
rand = "0.8"

futures = "0.3"
grapl-utils = { path = "../grapl-utils" }

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[build-dependencies]
prost-build = "0.7"
